 describe("flight_booking",()=>{
    it.skip("flight_booking_in_date_formate",()=>{
        cy.visit("https://onwardflightticket.com/")
        cy.get('[type="submit"]').click()
        cy.wait(4000)
        cy.get('[type="button"]').eq(1).click()
        cy.get("#firstName").type("hari")
        cy.get("#familyName").type("krishna")
        cy.get("#email").type("hari@gmail.com")
        cy.get("#agree_to_terms").check()
        cy.get('[type="submit"]').eq(1).click()
        cy.wait(2000)
        // cy.get('[allowtransparency="true"]').then((iframe)=>{
        //     let iframebody = iframe.contents().find("Debit or Credit Card")
        //     cy.wrap(iframebody).click()
        // })
        cy.get('#jsx-iframe-4e2d614aac').then(iframe => {
            let iframeContents = iframe.contents()
            let debitOrCreditCardElement = iframeContents.find(':contains("Debit or Credit Card")')
            cy.wrap(debitOrCreditCardElement).click()
          });
         // cy.get('[allowtransparency="true"]').its("0.contentDocument").its("body").find(':contains("Debit or Credit Card")').click()
        // cy.iframelode("#jsx-iframe-4e2d614aac")
        // cy.iframe("#jsx-iframe-4e2d614aac").find('[class="paypal-button-label-container"]').eq(1)
        // cy.contains("Debit or Credit Card").click()
        cy.get("#credit-card-number").type("5416065144182805")
        cy.get("#expiry-date").type("05/22")
        cy.get("#credit-card-security").type("672") 
        cy.get("#billingAddress.givenName").type("CHANDHU")
        cy.get("#billingAddress.familyName").type("sai")
        cy.get("#billingAddress.line1").type("chandhu sai")
        cy.get("#billingAddress.line1").type("chandhu sai")
        cy.get("#billingAddress.line2").type("billingAddress.line2")
        cy.get("#billingAddress.city").type("billingAddress.city")
        cy.get('[data-testid="dialing-code"]').type("524121")
        cy.get("#phone").type("9010896009")
        cy.get("#email").type("hari@gmail.com")
        cy.get('[name="shipToBillingAddress"]').click()
        cy.get("#submit-button").click() 
    })
it("tictet booking",()=>{
    cy.visit("https://tickets.paytm.com/flights/")
    cy.get("#departureDate").click()

})
 })